// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit.sql

package dbgen

import (
	"context"
)

const insertAdminAudit = `-- name: InsertAdminAudit :exec
INSERT INTO admin_audit (actor, action, target, payload)
VALUES ($1, $2, $3, $4)
`

type InsertAdminAuditParams struct {
	Actor   string
	Action  string
	Target  string
	Payload []byte
}

func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error {
	_, err := q.db.Exec(ctx, insertAdminAudit,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Payload,
	)
	return err
}

const listAdminAudit = `-- name: ListAdminAudit :many
SELECT id, actor, action, target, payload, at
FROM admin_audit
ORDER BY at DESC
LIMIT $1
`

func (q *Queries) ListAdminAudit(ctx context.Context, limit int32) ([]AdminAudit, error) {
	rows, err := q.db.Query(ctx, listAdminAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAudit
	for rows.Next() {
		var i AdminAudit
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Payload,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
