// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_users.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listDailyMetrics = `-- name: ListDailyMetrics :many
SELECT day, metric, dims, value FROM daily_metrics
WHERE day BETWEEN $1 AND $2 AND ($3::text = '' OR metric = $3)
ORDER BY day, metric
`

type ListDailyMetricsParams struct {
	Day     time.Time
	Day_2   time.Time
	Column3 string
}

func (q *Queries) ListDailyMetrics(ctx context.Context, arg ListDailyMetricsParams) ([]DailyMetric, error) {
	rows, err := q.db.Query(ctx, listDailyMetrics, arg.Day, arg.Day_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyMetric
	for rows.Next() {
		var i DailyMetric
		if err := rows.Scan(
			&i.Day,
			&i.Metric,
			&i.Dims,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, market, app_version, os_version, model, created_at, last_seen_at
FROM devices WHERE user_id = $1 ORDER BY created_at
`

type ListDevicesByUserRow struct {
	ID         uuid.UUID
	Market     string
	AppVersion string
	OsVersion  string
	Model      string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

func (q *Queries) ListDevicesByUser(ctx context.Context, userID uuid.UUID) ([]ListDevicesByUserRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesByUserRow
	for rows.Next() {
		var i ListDevicesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.AppVersion,
			&i.OsVersion,
			&i.Model,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsByUser = `-- name: ListGrantsByUser :many
SELECT id, user_id, entitlement, source, purchase_id, reason, starts_at, ends_at, revoked_at, created_at FROM entitlement_grants WHERE user_id = $1 ORDER BY starts_at
`

func (q *Queries) ListGrantsByUser(ctx context.Context, userID uuid.UUID) ([]EntitlementGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementGrant
	for rows.Next() {
		var i EntitlementGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Entitlement,
			&i.Source,
			&i.PurchaseID,
			&i.Reason,
			&i.StartsAt,
			&i.EndsAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasesByUser = `-- name: ListPurchasesByUser :many
SELECT id, market, product_id, state, purchased_at, expires_at, auto_renewing
FROM purchases WHERE user_id = $1 ORDER BY purchased_at
`

type ListPurchasesByUserRow struct {
	ID           uuid.UUID
	Market       string
	ProductID    string
	State        string
	PurchasedAt  time.Time
	ExpiresAt    *time.Time
	AutoRenewing bool
}

func (q *Queries) ListPurchasesByUser(ctx context.Context, userID uuid.UUID) ([]ListPurchasesByUserRow, error) {
	rows, err := q.db.Query(ctx, listPurchasesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchasesByUserRow
	for rows.Next() {
		var i ListPurchasesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.ProductID,
			&i.State,
			&i.PurchasedAt,
			&i.ExpiresAt,
			&i.AutoRenewing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
