// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteBackup = `-- name: DeleteBackup :execrows
DELETE FROM backups WHERE user_id = $1
`

func (q *Queries) DeleteBackup(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackup, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBackup = `-- name: GetBackup :one
SELECT user_id, storage, blob_ref, blob, size_bytes, schema_version, sha256, kdf_params, updated_at FROM backups WHERE user_id = $1
`

func (q *Queries) GetBackup(ctx context.Context, userID uuid.UUID) (Backup, error) {
	row := q.db.QueryRow(ctx, getBackup, userID)
	var i Backup
	err := row.Scan(
		&i.UserID,
		&i.Storage,
		&i.BlobRef,
		&i.Blob,
		&i.SizeBytes,
		&i.SchemaVersion,
		&i.Sha256,
		&i.KdfParams,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBackup = `-- name: UpsertBackup :exec
INSERT INTO backups (user_id, storage, blob_ref, blob, size_bytes, schema_version, sha256, kdf_params, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE SET storage = EXCLUDED.storage, blob_ref = EXCLUDED.blob_ref, blob = EXCLUDED.blob,
  size_bytes = EXCLUDED.size_bytes, schema_version = EXCLUDED.schema_version, sha256 = EXCLUDED.sha256,
  kdf_params = EXCLUDED.kdf_params, updated_at = EXCLUDED.updated_at
`

type UpsertBackupParams struct {
	UserID        uuid.UUID
	Storage       string
	BlobRef       string
	Blob          []byte
	SizeBytes     int32
	SchemaVersion int32
	Sha256        string
	KdfParams     []byte
	UpdatedAt     time.Time
}

func (q *Queries) UpsertBackup(ctx context.Context, arg UpsertBackupParams) error {
	_, err := q.db.Exec(ctx, upsertBackup,
		arg.UserID,
		arg.Storage,
		arg.BlobRef,
		arg.Blob,
		arg.SizeBytes,
		arg.SchemaVersion,
		arg.Sha256,
		arg.KdfParams,
		arg.UpdatedAt,
	)
	return err
}
