// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package dbgen

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertEvent = `-- name: InsertEvent :batchexec
WITH d AS (
  INSERT INTO events_dedupe (event_id, received_at) VALUES ($1, $9) ON CONFLICT (event_id) DO NOTHING RETURNING 1
)
INSERT INTO events (id, user_id, install_id, name, props, client_ts, received_at, app_version, market, session_id)
SELECT $1, $2, $3, $4, $5, $6, $9, $7, $8, $10 FROM d
`

type InsertEventBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertEventParams struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	InstallID  uuid.NullUUID
	Name       string
	Props      []byte
	ClientTs   time.Time
	AppVersion string
	Market     string
	ReceivedAt time.Time
	SessionID  string
}

func (q *Queries) InsertEvent(ctx context.Context, arg []InsertEventParams) *InsertEventBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.UserID,
			a.InstallID,
			a.Name,
			a.Props,
			a.ClientTs,
			a.AppVersion,
			a.Market,
			a.ReceivedAt,
			a.SessionID,
		}
		batch.Queue(insertEvent, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertEventBatchResults{br, len(arg), false}
}

func (b *InsertEventBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertEventBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
