// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package dbgen

import (
	"context"
	"time"
)

const activateConfig = `-- name: ActivateConfig :execrows
UPDATE config_versions SET is_active = true WHERE version = $1
`

func (q *Queries) ActivateConfig(ctx context.Context, version int32) (int64, error) {
	result, err := q.db.Exec(ctx, activateConfig, version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateConfigs = `-- name: DeactivateConfigs :exec
UPDATE config_versions SET is_active = false WHERE is_active
`

func (q *Queries) DeactivateConfigs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateConfigs)
	return err
}

const getActiveConfig = `-- name: GetActiveConfig :one
SELECT id, version, payload, min_app_version, published_at, published_by, is_active FROM config_versions WHERE is_active
`

func (q *Queries) GetActiveConfig(ctx context.Context) (ConfigVersion, error) {
	row := q.db.QueryRow(ctx, getActiveConfig)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Payload,
		&i.MinAppVersion,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.IsActive,
	)
	return i, err
}

const getConfigVersion = `-- name: GetConfigVersion :one
SELECT id, version, payload, min_app_version, published_at, published_by, is_active FROM config_versions WHERE version = $1
`

func (q *Queries) GetConfigVersion(ctx context.Context, version int32) (ConfigVersion, error) {
	row := q.db.QueryRow(ctx, getConfigVersion, version)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Payload,
		&i.MinAppVersion,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.IsActive,
	)
	return i, err
}

const getExperiment = `-- name: GetExperiment :one
SELECT key, status, variants, audience, started_at, stopped_at, updated_at FROM experiments WHERE key = $1
`

func (q *Queries) GetExperiment(ctx context.Context, key string) (Experiment, error) {
	row := q.db.QueryRow(ctx, getExperiment, key)
	var i Experiment
	err := row.Scan(
		&i.Key,
		&i.Status,
		&i.Variants,
		&i.Audience,
		&i.StartedAt,
		&i.StoppedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConfigVersion = `-- name: InsertConfigVersion :one
INSERT INTO config_versions (version, payload, min_app_version, published_by, published_at)
VALUES ((SELECT COALESCE(MAX(version), 0) + 1 FROM config_versions), $1, $2, $3, $4)
RETURNING id, version, payload, min_app_version, published_at, published_by, is_active
`

type InsertConfigVersionParams struct {
	Payload       []byte
	MinAppVersion string
	PublishedBy   string
	PublishedAt   time.Time
}

func (q *Queries) InsertConfigVersion(ctx context.Context, arg InsertConfigVersionParams) (ConfigVersion, error) {
	row := q.db.QueryRow(ctx, insertConfigVersion,
		arg.Payload,
		arg.MinAppVersion,
		arg.PublishedBy,
		arg.PublishedAt,
	)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Payload,
		&i.MinAppVersion,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.IsActive,
	)
	return i, err
}

const listRunningExperiments = `-- name: ListRunningExperiments :many
SELECT key, status, variants, audience, started_at, stopped_at, updated_at FROM experiments WHERE status = 'running' ORDER BY key
`

func (q *Queries) ListRunningExperiments(ctx context.Context) ([]Experiment, error) {
	rows, err := q.db.Query(ctx, listRunningExperiments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experiment
	for rows.Next() {
		var i Experiment
		if err := rows.Scan(
			&i.Key,
			&i.Status,
			&i.Variants,
			&i.Audience,
			&i.StartedAt,
			&i.StoppedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExperiment = `-- name: UpsertExperiment :exec
INSERT INTO experiments (key, status, variants, audience, started_at, stopped_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (key) DO UPDATE SET status = EXCLUDED.status, variants = EXCLUDED.variants,
  audience = EXCLUDED.audience, started_at = EXCLUDED.started_at, stopped_at = EXCLUDED.stopped_at,
  updated_at = EXCLUDED.updated_at
`

type UpsertExperimentParams struct {
	Key       string
	Status    string
	Variants  []byte
	Audience  []byte
	StartedAt *time.Time
	StoppedAt *time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertExperiment(ctx context.Context, arg UpsertExperimentParams) error {
	_, err := q.db.Exec(ctx, upsertExperiment,
		arg.Key,
		arg.Status,
		arg.Variants,
		arg.Audience,
		arg.StartedAt,
		arg.StoppedAt,
		arg.UpdatedAt,
	)
	return err
}
