// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package dbgen

import (
	"context"
	"time"
)

const getPackRaw = `-- name: GetPackRaw :one
SELECT raw, sha256 FROM content_packs WHERE pack_key = $1 AND version = $2 AND locale = 'fa' AND is_active
`

type GetPackRawParams struct {
	PackKey string
	Version int32
}

type GetPackRawRow struct {
	Raw    []byte
	Sha256 string
}

func (q *Queries) GetPackRaw(ctx context.Context, arg GetPackRawParams) (GetPackRawRow, error) {
	row := q.db.QueryRow(ctx, getPackRaw, arg.PackKey, arg.Version)
	var i GetPackRawRow
	err := row.Scan(&i.Raw, &i.Sha256)
	return i, err
}

const insertContentPack = `-- name: InsertContentPack :one
INSERT INTO content_packs (pack_key, version, locale, payload, raw, sha256, min_app_version, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, pack_key, version, locale, sha256, min_app_version, published_at
`

type InsertContentPackParams struct {
	PackKey       string
	Version       int32
	Locale        string
	Payload       []byte
	Raw           []byte
	Sha256        string
	MinAppVersion string
	PublishedAt   time.Time
}

type InsertContentPackRow struct {
	ID            int64
	PackKey       string
	Version       int32
	Locale        string
	Sha256        string
	MinAppVersion string
	PublishedAt   time.Time
}

func (q *Queries) InsertContentPack(ctx context.Context, arg InsertContentPackParams) (InsertContentPackRow, error) {
	row := q.db.QueryRow(ctx, insertContentPack,
		arg.PackKey,
		arg.Version,
		arg.Locale,
		arg.Payload,
		arg.Raw,
		arg.Sha256,
		arg.MinAppVersion,
		arg.PublishedAt,
	)
	var i InsertContentPackRow
	err := row.Scan(
		&i.ID,
		&i.PackKey,
		&i.Version,
		&i.Locale,
		&i.Sha256,
		&i.MinAppVersion,
		&i.PublishedAt,
	)
	return i, err
}

const listActivePackMeta = `-- name: ListActivePackMeta :many
SELECT pack_key, version, sha256, length(raw)::int AS size, min_app_version
FROM content_packs
WHERE is_active AND locale = 'fa'
ORDER BY pack_key, version DESC
`

type ListActivePackMetaRow struct {
	PackKey       string
	Version       int32
	Sha256        string
	Size          int32
	MinAppVersion string
}

func (q *Queries) ListActivePackMeta(ctx context.Context) ([]ListActivePackMetaRow, error) {
	rows, err := q.db.Query(ctx, listActivePackMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePackMetaRow
	for rows.Next() {
		var i ListActivePackMetaRow
		if err := rows.Scan(
			&i.PackKey,
			&i.Version,
			&i.Sha256,
			&i.Size,
			&i.MinAppVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
