// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUserDevices = `-- name: CountUserDevices :one
SELECT COUNT(*)::int FROM devices WHERE user_id = $1
`

func (q *Queries) CountUserDevices(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUserDevices, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, install_id, device_hash, market, app_version, os_version, model, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING id, user_id, install_id, device_hash, market, app_version, os_version, model, created_at, last_seen_at
`

type CreateDeviceParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	InstallID  uuid.UUID
	DeviceHash string
	Market     string
	AppVersion string
	OsVersion  string
	Model      string
	CreatedAt  time.Time
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.InstallID,
		arg.DeviceHash,
		arg.Market,
		arg.AppVersion,
		arg.OsVersion,
		arg.Model,
		arg.CreatedAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallID,
		&i.DeviceHash,
		&i.Market,
		&i.AppVersion,
		&i.OsVersion,
		&i.Model,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, install_id, device_hash, market, app_version, os_version, model, created_at, last_seen_at FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallID,
		&i.DeviceHash,
		&i.Market,
		&i.AppVersion,
		&i.OsVersion,
		&i.Model,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getDeviceByInstallID = `-- name: GetDeviceByInstallID :one
SELECT id, user_id, install_id, device_hash, market, app_version, os_version, model, created_at, last_seen_at FROM devices WHERE install_id = $1
`

func (q *Queries) GetDeviceByInstallID(ctx context.Context, installID uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByInstallID, installID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallID,
		&i.DeviceHash,
		&i.Market,
		&i.AppVersion,
		&i.OsVersion,
		&i.Model,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const rebindDevice = `-- name: RebindDevice :exec
UPDATE devices SET user_id = $2 WHERE id = $1
`

type RebindDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RebindDevice(ctx context.Context, arg RebindDeviceParams) error {
	_, err := q.db.Exec(ctx, rebindDevice, arg.ID, arg.UserID)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET app_version = $2, os_version = $3, model = $4, market = $5, last_seen_at = $6
WHERE id = $1
`

type TouchDeviceParams struct {
	ID         uuid.UUID
	AppVersion string
	OsVersion  string
	Model      string
	Market     string
	LastSeenAt time.Time
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.Exec(ctx, touchDevice,
		arg.ID,
		arg.AppVersion,
		arg.OsVersion,
		arg.Model,
		arg.Market,
		arg.LastSeenAt,
	)
	return err
}

const userHasDeviceHash = `-- name: UserHasDeviceHash :one
SELECT EXISTS (SELECT 1 FROM devices WHERE user_id = $1 AND device_hash = $2)
`

type UserHasDeviceHashParams struct {
	UserID     uuid.UUID
	DeviceHash string
}

func (q *Queries) UserHasDeviceHash(ctx context.Context, arg UserHasDeviceHashParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasDeviceHash, arg.UserID, arg.DeviceHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
