// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const anonymizeUserEvents = `-- name: AnonymizeUserEvents :exec
UPDATE events SET user_id = NULL WHERE user_id = $1
`

func (q *Queries) AnonymizeUserEvents(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, anonymizeUserEvents, userID)
	return err
}

const dropEventPartitionsBefore = `-- name: DropEventPartitionsBefore :one
SELECT drop_events_partitions_before($1::date)::int AS dropped
`

func (q *Queries) DropEventPartitionsBefore(ctx context.Context, dollar_1 time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, dropEventPartitionsBefore, dollar_1)
	var dropped int32
	err := row.Scan(&dropped)
	return dropped, err
}

const ensureEventsPartition = `-- name: EnsureEventsPartition :exec
SELECT ensure_events_partition($1::date)
`

func (q *Queries) EnsureEventsPartition(ctx context.Context, dollar_1 time.Time) error {
	_, err := q.db.Exec(ctx, ensureEventsPartition, dollar_1)
	return err
}

const pruneEventsDedupe = `-- name: PruneEventsDedupe :execrows
DELETE FROM events_dedupe WHERE received_at < $1
`

func (q *Queries) PruneEventsDedupe(ctx context.Context, receivedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEventsDedupe, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
