// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getGrantByPurchase = `-- name: GetGrantByPurchase :one
SELECT id, user_id, entitlement, source, purchase_id, reason, starts_at, ends_at, revoked_at, created_at FROM entitlement_grants WHERE purchase_id = $1 AND revoked_at IS NULL ORDER BY created_at LIMIT 1
`

func (q *Queries) GetGrantByPurchase(ctx context.Context, purchaseID uuid.NullUUID) (EntitlementGrant, error) {
	row := q.db.QueryRow(ctx, getGrantByPurchase, purchaseID)
	var i EntitlementGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Entitlement,
		&i.Source,
		&i.PurchaseID,
		&i.Reason,
		&i.StartsAt,
		&i.EndsAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO entitlement_grants (id, user_id, entitlement, source, purchase_id, reason, starts_at, ends_at, created_at)
VALUES ($1, $2, 'premium', $3, $4, $5, $6, $7, $8)
`

type InsertGrantParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Source     string
	PurchaseID uuid.NullUUID
	Reason     string
	StartsAt   time.Time
	EndsAt     time.Time
	CreatedAt  time.Time
}

func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.Exec(ctx, insertGrant,
		arg.ID,
		arg.UserID,
		arg.Source,
		arg.PurchaseID,
		arg.Reason,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedAt,
	)
	return err
}

const latestGrantEnd = `-- name: LatestGrantEnd :one
SELECT COALESCE(MAX(ends_at), 'epoch'::timestamptz)::timestamptz AS ends_at
FROM entitlement_grants
WHERE user_id = $1 AND entitlement = 'premium' AND revoked_at IS NULL
`

func (q *Queries) LatestGrantEnd(ctx context.Context, userID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestGrantEnd, userID)
	var ends_at time.Time
	err := row.Scan(&ends_at)
	return ends_at, err
}

const listActiveGrants = `-- name: ListActiveGrants :many
SELECT id, user_id, entitlement, source, purchase_id, reason, starts_at, ends_at, revoked_at, created_at FROM entitlement_grants
WHERE user_id = $1 AND revoked_at IS NULL AND $2 < ends_at -- includes queued (future-start) pass grants
ORDER BY starts_at, id
`

type ListActiveGrantsParams struct {
	UserID uuid.UUID
	EndsAt time.Time
}

func (q *Queries) ListActiveGrants(ctx context.Context, arg ListActiveGrantsParams) ([]EntitlementGrant, error) {
	rows, err := q.db.Query(ctx, listActiveGrants, arg.UserID, arg.EndsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementGrant
	for rows.Next() {
		var i EntitlementGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Entitlement,
			&i.Source,
			&i.PurchaseID,
			&i.Reason,
			&i.StartsAt,
			&i.EndsAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGrantsByPurchase = `-- name: RevokeGrantsByPurchase :exec
UPDATE entitlement_grants SET revoked_at = $2 WHERE purchase_id = $1 AND revoked_at IS NULL
`

type RevokeGrantsByPurchaseParams struct {
	PurchaseID uuid.NullUUID
	RevokedAt  *time.Time
}

func (q *Queries) RevokeGrantsByPurchase(ctx context.Context, arg RevokeGrantsByPurchaseParams) error {
	_, err := q.db.Exec(ctx, revokeGrantsByPurchase, arg.PurchaseID, arg.RevokedAt)
	return err
}

const revokeUserGrants = `-- name: RevokeUserGrants :exec
UPDATE entitlement_grants SET revoked_at = $2 WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeUserGrantsParams struct {
	UserID    uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeUserGrants(ctx context.Context, arg RevokeUserGrantsParams) error {
	_, err := q.db.Exec(ctx, revokeUserGrants, arg.UserID, arg.RevokedAt)
	return err
}

const updateGrantEnd = `-- name: UpdateGrantEnd :exec
UPDATE entitlement_grants SET ends_at = $2 WHERE id = $1
`

type UpdateGrantEndParams struct {
	ID     uuid.UUID
	EndsAt time.Time
}

func (q *Queries) UpdateGrantEnd(ctx context.Context, arg UpdateGrantEndParams) error {
	_, err := q.db.Exec(ctx, updateGrantEnd, arg.ID, arg.EndsAt)
	return err
}
