// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type AdminAudit struct {
	ID      int64
	Actor   string
	Action  string
	Target  string
	Payload []byte
	At      time.Time
}

type Device struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	InstallID  uuid.UUID
	DeviceHash string
	Market     string
	AppVersion string
	OsVersion  string
	Model      string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

type EntitlementGrant struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Entitlement string
	Source      string
	PurchaseID  uuid.NullUUID
	Reason      string
	StartsAt    time.Time
	EndsAt      time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type Product struct {
	ID           string
	Market       string
	Kind         string
	Entitlement  *string
	DurationDays *int32
	CoinsAmount  *int32
	MarketSku    string
	Active       bool
}

type Purchase struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	DeviceID          uuid.UUID
	Market            string
	ProductID         string
	MarketOrderID     string
	PurchaseTokenHash string
	PurchaseTokenEnc  []byte
	State             string
	PurchasedAt       time.Time
	VerifiedAt        *time.Time
	ExpiresAt         *time.Time
	AutoRenewing      bool
	RawResponse       []byte
	CreatedAt         time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	DeviceID  uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type Trial struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DeviceHash string
	StartedAt  time.Time
	EndsAt     time.Time
}

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	Status          string
	PhoneE164       *string
	PhoneVerifiedAt *time.Time
	DeletedAt       *time.Time
}
