// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type AdminAudit struct {
	ID      int64
	Actor   string
	Action  string
	Target  string
	Payload []byte
	At      time.Time
}

type Backup struct {
	UserID        uuid.UUID
	Blob          []byte
	SizeBytes     int32
	SchemaVersion int32
	Sha256        string
	KdfParams     []byte
	UpdatedAt     time.Time
}

type ConfigVersion struct {
	ID            int64
	Version       int32
	Payload       []byte
	MinAppVersion string
	PublishedAt   time.Time
	PublishedBy   string
	IsActive      bool
}

type ContentPack struct {
	ID            int64
	PackKey       string
	Version       int32
	Locale        string
	Payload       []byte
	Raw           []byte
	Sha256        string
	MinAppVersion string
	PublishedAt   time.Time
	IsActive      bool
}

type DailyMetric struct {
	Day    time.Time
	Metric string
	Dims   []byte
	Value  float64
}

type Device struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	InstallID  uuid.UUID
	DeviceHash string
	Market     string
	AppVersion string
	OsVersion  string
	Model      string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

type EntitlementGrant struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Entitlement string
	Source      string
	PurchaseID  uuid.NullUUID
	Reason      string
	StartsAt    time.Time
	EndsAt      time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type Event struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	InstallID  uuid.NullUUID
	Name       string
	Props      []byte
	ClientTs   time.Time
	ReceivedAt time.Time
	AppVersion string
	Market     string
	SessionID  string
}

type EventsDedupe struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Experiment struct {
	Key       string
	Status    string
	Variants  []byte
	Audience  []byte
	StartedAt *time.Time
	StoppedAt *time.Time
	UpdatedAt time.Time
}

type OperatorSession struct {
	ID         uuid.UUID
	OperatorID uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
}

type OtpChallenge struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	PhoneHash  string
	PhoneEnc   []byte
	CodeHash   string
	Attempts   int32
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type Product struct {
	ID           string
	Market       string
	Kind         string
	Entitlement  *string
	DurationDays *int32
	CoinsAmount  *int32
	MarketSku    string
	Active       bool
}

type Purchase struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	DeviceID          uuid.UUID
	Market            string
	ProductID         string
	MarketOrderID     string
	PurchaseTokenHash string
	PurchaseTokenEnc  []byte
	State             string
	PurchasedAt       time.Time
	VerifiedAt        *time.Time
	ExpiresAt         *time.Time
	AutoRenewing      bool
	RawResponse       []byte
	CreatedAt         time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	DeviceID  uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type SupportCannedReply struct {
	ID     uuid.UUID
	Key    string
	Title  string
	Body   string
	Active bool
}

type SupportConversation struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Status             string
	AssignedOperatorID uuid.NullUUID
	LastMessageAt      time.Time
	AwaitingSince      *time.Time
	UserUnreadCount    int32
	OperatorUnread     int32
	DeviceMeta         []byte
	CreatedAt          time.Time
	ClosedAt           *time.Time
}

type SupportMessage struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Sender         string
	OperatorID     uuid.NullUUID
	ClientMsgID    uuid.NullUUID
	BodyEnc        []byte
	CreatedAt      time.Time
	ReadAt         *time.Time
}

type SupportOperator struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  string
	Role         string
	Active       bool
	CreatedAt    time.Time
	LastLoginAt  *time.Time
}

type Trial struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DeviceHash string
	StartedAt  time.Time
	EndsAt     time.Time
}

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	Status          string
	PhoneVerifiedAt *time.Time
	DeletedAt       *time.Time
	PhoneEnc        []byte
	PhoneHash       *string
	PhoneLast4      *string
}
