// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAudit struct {
	ID      int64
	Actor   string
	Action  string
	Target  string
	Payload []byte
	At      time.Time
}

type Device struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	InstallID  uuid.UUID
	DeviceHash string
	Market     string
	AppVersion string
	OsVersion  string
	Model      string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	DeviceID  uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	Status          string
	PhoneE164       pgtype.Text
	PhoneVerifiedAt *time.Time
	DeletedAt       *time.Time
}
