// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpOTPAttempts = `-- name: BumpOTPAttempts :one
UPDATE otp_challenges SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) BumpOTPAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpOTPAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_challenges SET consumed_at = $2 WHERE id = $1 AND consumed_at IS NULL
`

type ConsumeOTPParams struct {
	ID         uuid.UUID
	ConsumedAt *time.Time
}

func (q *Queries) ConsumeOTP(ctx context.Context, arg ConsumeOTPParams) error {
	_, err := q.db.Exec(ctx, consumeOTP, arg.ID, arg.ConsumedAt)
	return err
}

const getOTPForUpdate = `-- name: GetOTPForUpdate :one
SELECT id, user_id, phone_hash, phone_enc, code_hash, attempts, expires_at, consumed_at, created_at FROM otp_challenges WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOTPForUpdate(ctx context.Context, id uuid.UUID) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, getOTPForUpdate, id)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneHash,
		&i.PhoneEnc,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOTPChallenge = `-- name: InsertOTPChallenge :exec
INSERT INTO otp_challenges (id, user_id, phone_hash, phone_enc, code_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOTPChallengeParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PhoneHash string
	PhoneEnc  []byte
	CodeHash  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertOTPChallenge(ctx context.Context, arg InsertOTPChallengeParams) error {
	_, err := q.db.Exec(ctx, insertOTPChallenge,
		arg.ID,
		arg.UserID,
		arg.PhoneHash,
		arg.PhoneEnc,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const oTPCountForUser = `-- name: OTPCountForUser :one
SELECT COUNT(*)::int AS sent FROM otp_challenges WHERE user_id = $1 AND created_at > $2
`

type OTPCountForUserParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) OTPCountForUser(ctx context.Context, arg OTPCountForUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, oTPCountForUser, arg.UserID, arg.CreatedAt)
	var sent int32
	err := row.Scan(&sent)
	return sent, err
}

const oTPStatsForPhone = `-- name: OTPStatsForPhone :one
SELECT COUNT(*) FILTER (WHERE created_at > $2)::int AS sent_in_window,
       COALESCE(MAX(created_at), 'epoch'::timestamptz)::timestamptz AS last_sent
FROM otp_challenges WHERE phone_hash = $1
`

type OTPStatsForPhoneParams struct {
	PhoneHash string
	CreatedAt time.Time
}

type OTPStatsForPhoneRow struct {
	SentInWindow int32
	LastSent     time.Time
}

func (q *Queries) OTPStatsForPhone(ctx context.Context, arg OTPStatsForPhoneParams) (OTPStatsForPhoneRow, error) {
	row := q.db.QueryRow(ctx, oTPStatsForPhone, arg.PhoneHash, arg.CreatedAt)
	var i OTPStatsForPhoneRow
	err := row.Scan(&i.SentInWindow, &i.LastSent)
	return i, err
}
