// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package dbgen

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, market, kind, entitlement, duration_days, coins_amount, market_sku, active FROM products WHERE id = $1 AND market = $2 AND active
`

type GetProductParams struct {
	ID     string
	Market string
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.Market)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.Kind,
		&i.Entitlement,
		&i.DurationDays,
		&i.CoinsAmount,
		&i.MarketSku,
		&i.Active,
	)
	return i, err
}

const getProductAnyState = `-- name: GetProductAnyState :one
SELECT id, market, kind, entitlement, duration_days, coins_amount, market_sku, active FROM products WHERE id = $1 AND market = $2
`

type GetProductAnyStateParams struct {
	ID     string
	Market string
}

func (q *Queries) GetProductAnyState(ctx context.Context, arg GetProductAnyStateParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductAnyState, arg.ID, arg.Market)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.Kind,
		&i.Entitlement,
		&i.DurationDays,
		&i.CoinsAmount,
		&i.MarketSku,
		&i.Active,
	)
	return i, err
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO products (id, market, kind, entitlement, duration_days, coins_amount, market_sku, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id, market) DO UPDATE SET kind = EXCLUDED.kind, entitlement = EXCLUDED.entitlement,
  duration_days = EXCLUDED.duration_days, coins_amount = EXCLUDED.coins_amount,
  market_sku = EXCLUDED.market_sku, active = EXCLUDED.active
`

type UpsertProductParams struct {
	ID           string
	Market       string
	Kind         string
	Entitlement  *string
	DurationDays *int32
	CoinsAmount  *int32
	MarketSku    string
	Active       bool
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.Exec(ctx, upsertProduct,
		arg.ID,
		arg.Market,
		arg.Kind,
		arg.Entitlement,
		arg.DurationDays,
		arg.CoinsAmount,
		arg.MarketSku,
		arg.Active,
	)
	return err
}
