// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchases.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPurchaseByToken = `-- name: GetPurchaseByToken :one
SELECT id, user_id, device_id, market, product_id, market_order_id, purchase_token_hash, purchase_token_enc, state, purchased_at, verified_at, expires_at, auto_renewing, raw_response, created_at FROM purchases WHERE market = $1 AND purchase_token_hash = $2
`

type GetPurchaseByTokenParams struct {
	Market            string
	PurchaseTokenHash string
}

func (q *Queries) GetPurchaseByToken(ctx context.Context, arg GetPurchaseByTokenParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, getPurchaseByToken, arg.Market, arg.PurchaseTokenHash)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Market,
		&i.ProductID,
		&i.MarketOrderID,
		&i.PurchaseTokenHash,
		&i.PurchaseTokenEnc,
		&i.State,
		&i.PurchasedAt,
		&i.VerifiedAt,
		&i.ExpiresAt,
		&i.AutoRenewing,
		&i.RawResponse,
		&i.CreatedAt,
	)
	return i, err
}

const insertPurchase = `-- name: InsertPurchase :one
INSERT INTO purchases (id, user_id, device_id, market, product_id, market_order_id, purchase_token_hash,
  purchase_token_enc, state, purchased_at, verified_at, expires_at, auto_renewing, raw_response, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, user_id, device_id, market, product_id, market_order_id, purchase_token_hash, purchase_token_enc, state, purchased_at, verified_at, expires_at, auto_renewing, raw_response, created_at
`

type InsertPurchaseParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	DeviceID          uuid.UUID
	Market            string
	ProductID         string
	MarketOrderID     string
	PurchaseTokenHash string
	PurchaseTokenEnc  []byte
	State             string
	PurchasedAt       time.Time
	VerifiedAt        *time.Time
	ExpiresAt         *time.Time
	AutoRenewing      bool
	RawResponse       []byte
	CreatedAt         time.Time
}

func (q *Queries) InsertPurchase(ctx context.Context, arg InsertPurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, insertPurchase,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.Market,
		arg.ProductID,
		arg.MarketOrderID,
		arg.PurchaseTokenHash,
		arg.PurchaseTokenEnc,
		arg.State,
		arg.PurchasedAt,
		arg.VerifiedAt,
		arg.ExpiresAt,
		arg.AutoRenewing,
		arg.RawResponse,
		arg.CreatedAt,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Market,
		&i.ProductID,
		&i.MarketOrderID,
		&i.PurchaseTokenHash,
		&i.PurchaseTokenEnc,
		&i.State,
		&i.PurchasedAt,
		&i.VerifiedAt,
		&i.ExpiresAt,
		&i.AutoRenewing,
		&i.RawResponse,
		&i.CreatedAt,
	)
	return i, err
}

const listPurchasesForReverify = `-- name: ListPurchasesForReverify :many
SELECT p.id, p.user_id, p.device_id, p.market, p.product_id, p.market_order_id, p.purchase_token_hash, p.purchase_token_enc, p.state, p.purchased_at, p.verified_at, p.expires_at, p.auto_renewing, p.raw_response, p.created_at FROM purchases p
JOIN products pr ON pr.id = p.product_id AND pr.market = p.market
WHERE pr.kind = 'subscription' AND p.state = 'verified'
  AND (p.expires_at < $1::timestamptz + interval '48 hours' OR p.purchased_at > $1::timestamptz - interval '7 days')
ORDER BY p.created_at
LIMIT $2
`

type ListPurchasesForReverifyParams struct {
	Column1 time.Time
	Limit   int32
}

func (q *Queries) ListPurchasesForReverify(ctx context.Context, arg ListPurchasesForReverifyParams) ([]Purchase, error) {
	rows, err := q.db.Query(ctx, listPurchasesForReverify, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Purchase
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Market,
			&i.ProductID,
			&i.MarketOrderID,
			&i.PurchaseTokenHash,
			&i.PurchaseTokenEnc,
			&i.State,
			&i.PurchasedAt,
			&i.VerifiedAt,
			&i.ExpiresAt,
			&i.AutoRenewing,
			&i.RawResponse,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferPurchase = `-- name: TransferPurchase :exec
UPDATE purchases SET user_id = $2, device_id = $3 WHERE id = $1
`

type TransferPurchaseParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	DeviceID uuid.UUID
}

func (q *Queries) TransferPurchase(ctx context.Context, arg TransferPurchaseParams) error {
	_, err := q.db.Exec(ctx, transferPurchase, arg.ID, arg.UserID, arg.DeviceID)
	return err
}

const updatePurchaseVerification = `-- name: UpdatePurchaseVerification :exec
UPDATE purchases SET state = $2, verified_at = $3, expires_at = $4, auto_renewing = $5, raw_response = $6
WHERE id = $1
`

type UpdatePurchaseVerificationParams struct {
	ID           uuid.UUID
	State        string
	VerifiedAt   *time.Time
	ExpiresAt    *time.Time
	AutoRenewing bool
	RawResponse  []byte
}

func (q *Queries) UpdatePurchaseVerification(ctx context.Context, arg UpdatePurchaseVerificationParams) error {
	_, err := q.db.Exec(ctx, updatePurchaseVerification,
		arg.ID,
		arg.State,
		arg.VerifiedAt,
		arg.ExpiresAt,
		arg.AutoRenewing,
		arg.RawResponse,
	)
	return err
}
