// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT rt.id, rt.device_id, rt.token_hash, rt.family_id, rt.expires_at, rt.revoked_at, d.user_id
FROM refresh_tokens rt
JOIN devices d ON d.id = rt.device_id
WHERE rt.token_hash = $1
FOR UPDATE OF rt
`

type GetRefreshTokenForUpdateRow struct {
	ID        uuid.UUID
	DeviceID  uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt *time.Time
	UserID    uuid.UUID
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, device_id, token_hash, family_id, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRefreshTokenParams struct {
	ID        uuid.UUID
	DeviceID  uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.DeviceID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const revokeDeviceTokens = `-- name: RevokeDeviceTokens :exec
UPDATE refresh_tokens SET revoked_at = $2 WHERE device_id = $1 AND revoked_at IS NULL
`

type RevokeDeviceTokensParams struct {
	DeviceID  uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeDeviceTokens(ctx context.Context, arg RevokeDeviceTokensParams) error {
	_, err := q.db.Exec(ctx, revokeDeviceTokens, arg.DeviceID, arg.RevokedAt)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = $2 WHERE id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.RevokedAt)
	return err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE refresh_tokens SET revoked_at = $2 WHERE family_id = $1 AND revoked_at IS NULL
`

type RevokeTokenFamilyParams struct {
	FamilyID  uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, arg.FamilyID, arg.RevokedAt)
	return err
}

const revokeUserTokens = `-- name: RevokeUserTokens :exec
UPDATE refresh_tokens SET revoked_at = $2
WHERE revoked_at IS NULL AND device_id IN (SELECT id FROM devices WHERE user_id = $1)
`

type RevokeUserTokensParams struct {
	UserID    uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeUserTokens(ctx context.Context, arg RevokeUserTokensParams) error {
	_, err := q.db.Exec(ctx, revokeUserTokens, arg.UserID, arg.RevokedAt)
	return err
}
