// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollup.sql

package dbgen

import (
	"context"
	"time"
)

const deleteDailyMetrics = `-- name: DeleteDailyMetrics :exec

DELETE FROM daily_metrics WHERE day = $1::date
`

// Daily rollups (docs/70 §5). Window bounds are UTC and passed by the caller. The "actor" of an
// event is its install_id (stable across account deletion), falling back to user_id.
func (q *Queries) DeleteDailyMetrics(ctx context.Context, day time.Time) error {
	_, err := q.db.Exec(ctx, deleteDailyMetrics, day)
	return err
}

const rollupActivation = `-- name: RollupActivation :exec
WITH onb AS (
  SELECT COALESCE(install_id, user_id) AS actor, MIN(received_at) AS t FROM events
  WHERE name = 'onboarding_completed' AND received_at >= $2::timestamptz AND received_at < $3::timestamptz
    AND COALESCE(install_id, user_id) IS NOT NULL
  GROUP BY 1
), act AS (
  SELECT DISTINCT o.actor FROM onb o JOIN events e
    ON COALESCE(e.install_id, e.user_id) = o.actor AND e.name = 'habit_completed'
   AND e.received_at >= o.t AND e.received_at < o.t + interval '24 hours'
)
INSERT INTO daily_metrics (day, metric, dims, value)
SELECT $1::date, 'activation_rate', '{}'::jsonb, (SELECT COUNT(*) FROM act)::float8 / COUNT(*) FROM onb HAVING COUNT(*) > 0
`

type RollupActivationParams struct {
	Day         time.Time
	WindowStart time.Time
	WindowEnd   time.Time
}

func (q *Queries) RollupActivation(ctx context.Context, arg RollupActivationParams) error {
	_, err := q.db.Exec(ctx, rollupActivation, arg.Day, arg.WindowStart, arg.WindowEnd)
	return err
}

const rollupActiveUsers = `-- name: RollupActiveUsers :exec
INSERT INTO daily_metrics (day, metric, dims, value)
SELECT $1::date, $2::text, '{}'::jsonb, COUNT(DISTINCT COALESCE(install_id, user_id))
FROM events
WHERE name = 'app_opened' AND received_at >= $3::timestamptz AND received_at < $4::timestamptz
`

type RollupActiveUsersParams struct {
	Day         time.Time
	Metric      string
	WindowStart time.Time
	WindowEnd   time.Time
}

func (q *Queries) RollupActiveUsers(ctx context.Context, arg RollupActiveUsersParams) error {
	_, err := q.db.Exec(ctx, rollupActiveUsers,
		arg.Day,
		arg.Metric,
		arg.WindowStart,
		arg.WindowEnd,
	)
	return err
}

const rollupCoreLoop = `-- name: RollupCoreLoop :exec
WITH dau AS (
  SELECT DISTINCT COALESCE(install_id, user_id) AS actor FROM events
  WHERE name = 'app_opened' AND received_at >= $2::timestamptz AND received_at < $3::timestamptz
), adv AS (
  SELECT DISTINCT COALESCE(install_id, user_id) AS actor FROM events
  WHERE name = 'adventure_started' AND received_at >= $2::timestamptz AND received_at < $3::timestamptz
)
INSERT INTO daily_metrics (day, metric, dims, value)
SELECT $1::date, 'core_loop_completion', '{}'::jsonb,
       (SELECT COUNT(*) FROM dau JOIN adv USING (actor))::float8 / COUNT(*) FROM dau HAVING COUNT(*) > 0
`

type RollupCoreLoopParams struct {
	Day         time.Time
	WindowStart time.Time
	WindowEnd   time.Time
}

func (q *Queries) RollupCoreLoop(ctx context.Context, arg RollupCoreLoopParams) error {
	_, err := q.db.Exec(ctx, rollupCoreLoop, arg.Day, arg.WindowStart, arg.WindowEnd)
	return err
}

const rollupNewInstalls = `-- name: RollupNewInstalls :exec
INSERT INTO daily_metrics (day, metric, dims, value)
SELECT $1::date, 'new_installs', '{}'::jsonb, COUNT(DISTINCT COALESCE(install_id, user_id))
FROM events
WHERE name = 'app_installed' AND received_at >= $2::timestamptz AND received_at < $3::timestamptz
`

type RollupNewInstallsParams struct {
	Day         time.Time
	WindowStart time.Time
	WindowEnd   time.Time
}

func (q *Queries) RollupNewInstalls(ctx context.Context, arg RollupNewInstallsParams) error {
	_, err := q.db.Exec(ctx, rollupNewInstalls, arg.Day, arg.WindowStart, arg.WindowEnd)
	return err
}

const rollupPaywall = `-- name: RollupPaywall :exec
WITH views AS (
  SELECT session_id, props->>'trigger' AS trigger, COALESCE(props->>'variant', '') AS variant, MIN(received_at) AS t
  FROM events
  WHERE name = 'paywall_viewed' AND session_id <> '' AND received_at >= $2::timestamptz AND received_at < $3::timestamptz
  GROUP BY 1, 2, 3
), agg AS (
  SELECT v.trigger, v.variant, COUNT(*) AS views,
         COUNT(*) FILTER (WHERE EXISTS (
           SELECT 1 FROM events p WHERE p.name = 'purchase_completed' AND p.session_id = v.session_id
             AND p.received_at >= v.t AND p.received_at < $3::timestamptz)) AS conv
  FROM views v GROUP BY 1, 2
), ins_views AS (
  INSERT INTO daily_metrics (day, metric, dims, value)
  SELECT $1::date, 'paywall_views', jsonb_build_object('trigger', trigger, 'variant', variant), views FROM agg
  RETURNING 1
)
INSERT INTO daily_metrics (day, metric, dims, value)
SELECT $1::date, 'paywall_cvr', jsonb_build_object('trigger', trigger, 'variant', variant), conv::float8 / views FROM agg WHERE views > 0
`

type RollupPaywallParams struct {
	Day         time.Time
	WindowStart time.Time
	WindowEnd   time.Time
}

func (q *Queries) RollupPaywall(ctx context.Context, arg RollupPaywallParams) error {
	_, err := q.db.Exec(ctx, rollupPaywall, arg.Day, arg.WindowStart, arg.WindowEnd)
	return err
}

const rollupRetention = `-- name: RollupRetention :exec
WITH cohort AS (
  SELECT DISTINCT COALESCE(install_id, user_id) AS actor FROM events
  WHERE name = 'app_installed' AND received_at >= $4::timestamptz AND received_at < $5::timestamptz
    AND COALESCE(install_id, user_id) IS NOT NULL
), returned AS (
  SELECT DISTINCT COALESCE(install_id, user_id) AS actor FROM events
  WHERE name = 'app_opened' AND received_at >= $6::timestamptz AND received_at < $7::timestamptz
), sizes AS (
  SELECT (SELECT COUNT(*) FROM cohort) AS total, (SELECT COUNT(*) FROM cohort c JOIN returned r USING (actor)) AS back
)
INSERT INTO daily_metrics (day, metric, dims, value)
SELECT $1::date, $2::text,
       jsonb_build_object('cohort_day', $3::text, 'cohort_size', total),
       back::float8 / total
FROM sizes WHERE total > 0
`

type RollupRetentionParams struct {
	Day         time.Time
	Metric      string
	CohortDay   string
	CohortStart time.Time
	CohortEnd   time.Time
	WindowStart time.Time
	WindowEnd   time.Time
}

func (q *Queries) RollupRetention(ctx context.Context, arg RollupRetentionParams) error {
	_, err := q.db.Exec(ctx, rollupRetention,
		arg.Day,
		arg.Metric,
		arg.CohortDay,
		arg.CohortStart,
		arg.CohortEnd,
		arg.WindowStart,
		arg.WindowEnd,
	)
	return err
}

const rollupStickiness = `-- name: RollupStickiness :exec
INSERT INTO daily_metrics (day, metric, dims, value)
SELECT d.day, 'stickiness', '{}'::jsonb, d.value / m.value
FROM daily_metrics d JOIN daily_metrics m ON m.day = d.day AND m.metric = 'mau' AND m.dims = '{}'::jsonb
WHERE d.day = $1::date AND d.metric = 'dau' AND d.dims = '{}'::jsonb AND m.value > 0
`

func (q *Queries) RollupStickiness(ctx context.Context, day time.Time) error {
	_, err := q.db.Exec(ctx, rollupStickiness, day)
	return err
}

const rollupTrialStartRate = `-- name: RollupTrialStartRate :exec
WITH onb AS (
  SELECT COUNT(DISTINCT COALESCE(install_id, user_id)) AS n FROM events
  WHERE name = 'onboarding_completed' AND received_at >= $2::timestamptz AND received_at < $3::timestamptz
), tr AS (
  SELECT COUNT(DISTINCT COALESCE(install_id, user_id)) AS n FROM events
  WHERE name = 'trial_started' AND received_at >= $2::timestamptz AND received_at < $3::timestamptz
)
INSERT INTO daily_metrics (day, metric, dims, value)
SELECT $1::date, 'trial_start_rate', '{}'::jsonb, tr.n::float8 / onb.n FROM onb, tr WHERE onb.n > 0
`

type RollupTrialStartRateParams struct {
	Day         time.Time
	WindowStart time.Time
	WindowEnd   time.Time
}

func (q *Queries) RollupTrialStartRate(ctx context.Context, arg RollupTrialStartRateParams) error {
	_, err := q.db.Exec(ctx, rollupTrialStartRate, arg.Day, arg.WindowStart, arg.WindowEnd)
	return err
}
