// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const areFriends = `-- name: AreFriends :one
SELECT EXISTS (SELECT 1 FROM friendships WHERE user_a = $1 AND user_b = $2) AS ok
`

type AreFriendsParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.UserA, arg.UserB)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const countFriends = `-- name: CountFriends :one
SELECT COUNT(*)::int AS n FROM friendships WHERE user_a = $1 OR user_b = $1
`

func (q *Queries) CountFriends(ctx context.Context, userA uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFriends, userA)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships WHERE user_a = $1 AND user_b = $2
`

type DeleteFriendshipParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.UserA, arg.UserB)
	return err
}

const deleteUserSocial = `-- name: DeleteUserSocial :exec
WITH f AS (DELETE FROM friendships WHERE user_a = $1 OR user_b = $1),
     v AS (DELETE FROM vibes WHERE from_user = $1 OR to_user = $1)
DELETE FROM social_profiles WHERE user_id = $1
`

func (q *Queries) DeleteUserSocial(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSocial, userID)
	return err
}

const getSocialProfile = `-- name: GetSocialProfile :one
SELECT user_id, friend_code, nickname, cat_name, cat_fur, cat_stage, cat_hue, updated_at FROM social_profiles WHERE user_id = $1
`

func (q *Queries) GetSocialProfile(ctx context.Context, userID uuid.UUID) (SocialProfile, error) {
	row := q.db.QueryRow(ctx, getSocialProfile, userID)
	var i SocialProfile
	err := row.Scan(
		&i.UserID,
		&i.FriendCode,
		&i.Nickname,
		&i.CatName,
		&i.CatFur,
		&i.CatStage,
		&i.CatHue,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialProfileByCode = `-- name: GetSocialProfileByCode :one
SELECT sp.user_id, sp.friend_code, sp.nickname, sp.cat_name, sp.cat_fur, sp.cat_stage, sp.cat_hue, sp.updated_at FROM social_profiles sp JOIN users u ON u.id = sp.user_id
WHERE sp.friend_code = $1 AND u.status = 'active'
`

func (q *Queries) GetSocialProfileByCode(ctx context.Context, friendCode string) (SocialProfile, error) {
	row := q.db.QueryRow(ctx, getSocialProfileByCode, friendCode)
	var i SocialProfile
	err := row.Scan(
		&i.UserID,
		&i.FriendCode,
		&i.Nickname,
		&i.CatName,
		&i.CatFur,
		&i.CatStage,
		&i.CatHue,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFriendship = `-- name: InsertFriendship :exec
INSERT INTO friendships (user_a, user_b, created_at) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertFriendshipParams struct {
	UserA     uuid.UUID
	UserB     uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertFriendship(ctx context.Context, arg InsertFriendshipParams) error {
	_, err := q.db.Exec(ctx, insertFriendship, arg.UserA, arg.UserB, arg.CreatedAt)
	return err
}

const insertSocialProfile = `-- name: InsertSocialProfile :exec
INSERT INTO social_profiles (user_id, friend_code, updated_at) VALUES ($1, $2, $3)
`

type InsertSocialProfileParams struct {
	UserID     uuid.UUID
	FriendCode string
	UpdatedAt  time.Time
}

func (q *Queries) InsertSocialProfile(ctx context.Context, arg InsertSocialProfileParams) error {
	_, err := q.db.Exec(ctx, insertSocialProfile, arg.UserID, arg.FriendCode, arg.UpdatedAt)
	return err
}

const insertVibe = `-- name: InsertVibe :execrows
INSERT INTO vibes (id, from_user, to_user, kind, day, created_at) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (from_user, to_user, day) DO NOTHING
`

type InsertVibeParams struct {
	ID        uuid.UUID
	FromUser  uuid.UUID
	ToUser    uuid.UUID
	Kind      string
	Day       time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertVibe(ctx context.Context, arg InsertVibeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVibe,
		arg.ID,
		arg.FromUser,
		arg.ToUser,
		arg.Kind,
		arg.Day,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFriendIDs = `-- name: ListFriendIDs :many
SELECT CASE WHEN user_a = $1 THEN user_b ELSE user_a END::uuid AS friend FROM friendships WHERE user_a = $1 OR user_b = $1
`

func (q *Queries) ListFriendIDs(ctx context.Context, userA uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFriendIDs, userA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var friend uuid.UUID
		if err := rows.Scan(&friend); err != nil {
			return nil, err
		}
		items = append(items, friend)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT sp.user_id, sp.friend_code, sp.nickname, sp.cat_name, sp.cat_fur, sp.cat_stage, sp.cat_hue, f.created_at AS since,
       EXISTS (SELECT 1 FROM vibes v WHERE v.from_user = $1 AND v.to_user = sp.user_id AND v.day = $2::date) AS vibed_today
FROM friendships f
JOIN social_profiles sp ON sp.user_id = CASE WHEN f.user_a = $1 THEN f.user_b ELSE f.user_a END
JOIN users u ON u.id = sp.user_id AND u.status = 'active'
WHERE f.user_a = $1 OR f.user_b = $1
ORDER BY f.created_at
`

type ListFriendsParams struct {
	Me  uuid.UUID
	Day time.Time
}

type ListFriendsRow struct {
	UserID     uuid.UUID
	FriendCode string
	Nickname   string
	CatName    string
	CatFur     string
	CatStage   string
	CatHue     int32
	Since      time.Time
	VibedToday bool
}

func (q *Queries) ListFriends(ctx context.Context, arg ListFriendsParams) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, arg.Me, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsRow
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.UserID,
			&i.FriendCode,
			&i.Nickname,
			&i.CatName,
			&i.CatFur,
			&i.CatStage,
			&i.CatHue,
			&i.Since,
			&i.VibedToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedVibes = `-- name: ListReceivedVibes :many
SELECT v.id, v.kind, v.created_at, v.read_at, sp.friend_code, sp.nickname, sp.cat_name
FROM vibes v JOIN social_profiles sp ON sp.user_id = v.from_user
WHERE v.to_user = $1 AND v.created_at > $2
ORDER BY v.created_at DESC
LIMIT 100
`

type ListReceivedVibesParams struct {
	ToUser    uuid.UUID
	CreatedAt time.Time
}

type ListReceivedVibesRow struct {
	ID         uuid.UUID
	Kind       string
	CreatedAt  time.Time
	ReadAt     *time.Time
	FriendCode string
	Nickname   string
	CatName    string
}

func (q *Queries) ListReceivedVibes(ctx context.Context, arg ListReceivedVibesParams) ([]ListReceivedVibesRow, error) {
	rows, err := q.db.Query(ctx, listReceivedVibes, arg.ToUser, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivedVibesRow
	for rows.Next() {
		var i ListReceivedVibesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CreatedAt,
			&i.ReadAt,
			&i.FriendCode,
			&i.Nickname,
			&i.CatName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVibesRead = `-- name: MarkVibesRead :exec
UPDATE vibes SET read_at = $2 WHERE to_user = $1 AND read_at IS NULL
`

type MarkVibesReadParams struct {
	ToUser uuid.UUID
	ReadAt *time.Time
}

func (q *Queries) MarkVibesRead(ctx context.Context, arg MarkVibesReadParams) error {
	_, err := q.db.Exec(ctx, markVibesRead, arg.ToUser, arg.ReadAt)
	return err
}

const updateSocialProfile = `-- name: UpdateSocialProfile :exec
UPDATE social_profiles SET nickname = $2, cat_name = $3, cat_fur = $4, cat_stage = $5, cat_hue = $6, updated_at = $7
WHERE user_id = $1
`

type UpdateSocialProfileParams struct {
	UserID    uuid.UUID
	Nickname  string
	CatName   string
	CatFur    string
	CatStage  string
	CatHue    int32
	UpdatedAt time.Time
}

func (q *Queries) UpdateSocialProfile(ctx context.Context, arg UpdateSocialProfileParams) error {
	_, err := q.db.Exec(ctx, updateSocialProfile,
		arg.UserID,
		arg.Nickname,
		arg.CatName,
		arg.CatFur,
		arg.CatStage,
		arg.CatHue,
		arg.UpdatedAt,
	)
	return err
}
