// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignConversation = `-- name: AssignConversation :exec
UPDATE support_conversations SET assigned_operator_id = $2 WHERE id = $1
`

type AssignConversationParams struct {
	ID                 uuid.UUID
	AssignedOperatorID uuid.NullUUID
}

func (q *Queries) AssignConversation(ctx context.Context, arg AssignConversationParams) error {
	_, err := q.db.Exec(ctx, assignConversation, arg.ID, arg.AssignedOperatorID)
	return err
}

const clearOperatorUnread = `-- name: ClearOperatorUnread :exec
UPDATE support_conversations SET operator_unread = 0 WHERE id = $1
`

func (q *Queries) ClearOperatorUnread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearOperatorUnread, id)
	return err
}

const closeConversation = `-- name: CloseConversation :exec
UPDATE support_conversations SET status = 'closed', closed_at = $2, awaiting_since = NULL WHERE id = $1
`

type CloseConversationParams struct {
	ID       uuid.UUID
	ClosedAt *time.Time
}

func (q *Queries) CloseConversation(ctx context.Context, arg CloseConversationParams) error {
	_, err := q.db.Exec(ctx, closeConversation, arg.ID, arg.ClosedAt)
	return err
}

const conversationOperatorMessage = `-- name: ConversationOperatorMessage :exec
UPDATE support_conversations SET status = 'waiting_user', last_message_at = $2, awaiting_since = NULL,
  user_unread_count = user_unread_count + 1, operator_unread = 0,
  assigned_operator_id = COALESCE(assigned_operator_id, $3)
WHERE id = $1
`

type ConversationOperatorMessageParams struct {
	ID                 uuid.UUID
	LastMessageAt      time.Time
	AssignedOperatorID uuid.NullUUID
}

func (q *Queries) ConversationOperatorMessage(ctx context.Context, arg ConversationOperatorMessageParams) error {
	_, err := q.db.Exec(ctx, conversationOperatorMessage, arg.ID, arg.LastMessageAt, arg.AssignedOperatorID)
	return err
}

const conversationUserMessage = `-- name: ConversationUserMessage :exec
UPDATE support_conversations SET status = 'open', closed_at = NULL, last_message_at = $2,
  awaiting_since = COALESCE(awaiting_since, $2), operator_unread = operator_unread + 1,
  device_meta = COALESCE($3::jsonb, device_meta)
WHERE id = $1
`

type ConversationUserMessageParams struct {
	ID            uuid.UUID
	LastMessageAt time.Time
	DeviceMeta    []byte
}

func (q *Queries) ConversationUserMessage(ctx context.Context, arg ConversationUserMessageParams) error {
	_, err := q.db.Exec(ctx, conversationUserMessage, arg.ID, arg.LastMessageAt, arg.DeviceMeta)
	return err
}

const countOpenConversations = `-- name: CountOpenConversations :one
SELECT count(*) FROM support_conversations WHERE status <> 'closed'
`

func (q *Queries) CountOpenConversations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenConversations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO support_conversations (id, user_id, status, last_message_at, created_at)
VALUES ($1, $2, 'open', $3, $3) RETURNING id, user_id, status, assigned_operator_id, last_message_at, awaiting_since, user_unread_count, operator_unread, device_meta, created_at, closed_at
`

type CreateConversationParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	LastMessageAt time.Time
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.ID, arg.UserID, arg.LastMessageAt)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.AssignedOperatorID,
		&i.LastMessageAt,
		&i.AwaitingSince,
		&i.UserUnreadCount,
		&i.OperatorUnread,
		&i.DeviceMeta,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const deleteCanned = `-- name: DeleteCanned :exec
DELETE FROM support_canned_replies WHERE key = $1
`

func (q *Queries) DeleteCanned(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteCanned, key)
	return err
}

const deleteClosedConversationsBefore = `-- name: DeleteClosedConversationsBefore :execrows
DELETE FROM support_conversations WHERE status = 'closed' AND closed_at < $1
`

func (q *Queries) DeleteClosedConversationsBefore(ctx context.Context, closedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClosedConversationsBefore, closedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConversationsByUser = `-- name: DeleteConversationsByUser :exec
DELETE FROM support_conversations WHERE user_id = $1
`

func (q *Queries) DeleteConversationsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationsByUser, userID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, status, assigned_operator_id, last_message_at, awaiting_since, user_unread_count, operator_unread, device_meta, created_at, closed_at FROM support_conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.AssignedOperatorID,
		&i.LastMessageAt,
		&i.AwaitingSince,
		&i.UserUnreadCount,
		&i.OperatorUnread,
		&i.DeviceMeta,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getConversationForUpdate = `-- name: GetConversationForUpdate :one
SELECT id, user_id, status, assigned_operator_id, last_message_at, awaiting_since, user_unread_count, operator_unread, device_meta, created_at, closed_at FROM support_conversations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetConversationForUpdate(ctx context.Context, id uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, getConversationForUpdate, id)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.AssignedOperatorID,
		&i.LastMessageAt,
		&i.AwaitingSince,
		&i.UserUnreadCount,
		&i.OperatorUnread,
		&i.DeviceMeta,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getLatestConversationByUser = `-- name: GetLatestConversationByUser :one
SELECT id, user_id, status, assigned_operator_id, last_message_at, awaiting_since, user_unread_count, operator_unread, device_meta, created_at, closed_at FROM support_conversations WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestConversationByUser(ctx context.Context, userID uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, getLatestConversationByUser, userID)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.AssignedOperatorID,
		&i.LastMessageAt,
		&i.AwaitingSince,
		&i.UserUnreadCount,
		&i.OperatorUnread,
		&i.DeviceMeta,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, sender, operator_id, client_msg_id, body_enc, created_at, read_at FROM support_messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (SupportMessage, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i SupportMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Sender,
		&i.OperatorID,
		&i.ClientMsgID,
		&i.BodyEnc,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getMessageByClientID = `-- name: GetMessageByClientID :one
SELECT id, conversation_id, sender, operator_id, client_msg_id, body_enc, created_at, read_at FROM support_messages WHERE conversation_id = $1 AND client_msg_id = $2
`

type GetMessageByClientIDParams struct {
	ConversationID uuid.UUID
	ClientMsgID    uuid.NullUUID
}

func (q *Queries) GetMessageByClientID(ctx context.Context, arg GetMessageByClientIDParams) (SupportMessage, error) {
	row := q.db.QueryRow(ctx, getMessageByClientID, arg.ConversationID, arg.ClientMsgID)
	var i SupportMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Sender,
		&i.OperatorID,
		&i.ClientMsgID,
		&i.BodyEnc,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getOpenConversationByUser = `-- name: GetOpenConversationByUser :one
SELECT id, user_id, status, assigned_operator_id, last_message_at, awaiting_since, user_unread_count, operator_unread, device_meta, created_at, closed_at FROM support_conversations WHERE user_id = $1 AND status <> 'closed'
`

func (q *Queries) GetOpenConversationByUser(ctx context.Context, userID uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, getOpenConversationByUser, userID)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.AssignedOperatorID,
		&i.LastMessageAt,
		&i.AwaitingSince,
		&i.UserUnreadCount,
		&i.OperatorUnread,
		&i.DeviceMeta,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOperator = `-- name: GetOperator :one
SELECT id, username, password_hash, display_name, role, active, created_at, last_login_at FROM support_operators WHERE id = $1
`

func (q *Queries) GetOperator(ctx context.Context, id uuid.UUID) (SupportOperator, error) {
	row := q.db.QueryRow(ctx, getOperator, id)
	var i SupportOperator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getOperatorByUsername = `-- name: GetOperatorByUsername :one
SELECT id, username, password_hash, display_name, role, active, created_at, last_login_at FROM support_operators WHERE username = $1
`

func (q *Queries) GetOperatorByUsername(ctx context.Context, username string) (SupportOperator, error) {
	row := q.db.QueryRow(ctx, getOperatorByUsername, username)
	var i SupportOperator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getOperatorSession = `-- name: GetOperatorSession :one
SELECT s.id AS session_id, s.expires_at, s.revoked_at, o.id AS operator_id, o.username, o.display_name, o.role, o.active
FROM operator_sessions s JOIN support_operators o ON o.id = s.operator_id WHERE s.token_hash = $1
`

type GetOperatorSessionRow struct {
	SessionID   uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	OperatorID  uuid.UUID
	Username    string
	DisplayName string
	Role        string
	Active      bool
}

func (q *Queries) GetOperatorSession(ctx context.Context, tokenHash string) (GetOperatorSessionRow, error) {
	row := q.db.QueryRow(ctx, getOperatorSession, tokenHash)
	var i GetOperatorSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.OperatorID,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.Active,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO support_messages (id, conversation_id, sender, operator_id, client_msg_id, body_enc, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (conversation_id, client_msg_id) WHERE client_msg_id IS NOT NULL DO NOTHING
RETURNING id, conversation_id, sender, operator_id, client_msg_id, body_enc, created_at, read_at
`

type InsertMessageParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Sender         string
	OperatorID     uuid.NullUUID
	ClientMsgID    uuid.NullUUID
	BodyEnc        []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (SupportMessage, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.Sender,
		arg.OperatorID,
		arg.ClientMsgID,
		arg.BodyEnc,
		arg.CreatedAt,
	)
	var i SupportMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Sender,
		&i.OperatorID,
		&i.ClientMsgID,
		&i.BodyEnc,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const insertOperator = `-- name: InsertOperator :exec
INSERT INTO support_operators (id, username, password_hash, display_name, role, active, created_at)
VALUES ($1, $2, $3, $4, $5, true, $6)
`

type InsertOperatorParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  string
	Role         string
	CreatedAt    time.Time
}

func (q *Queries) InsertOperator(ctx context.Context, arg InsertOperatorParams) error {
	_, err := q.db.Exec(ctx, insertOperator,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const insertOperatorSession = `-- name: InsertOperatorSession :exec
INSERT INTO operator_sessions (id, operator_id, token_hash, expires_at, created_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertOperatorSessionParams struct {
	ID         uuid.UUID
	OperatorID uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	CreatedAt  time.Time
}

func (q *Queries) InsertOperatorSession(ctx context.Context, arg InsertOperatorSessionParams) error {
	_, err := q.db.Exec(ctx, insertOperatorSession,
		arg.ID,
		arg.OperatorID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listCanned = `-- name: ListCanned :many
SELECT id, key, title, body, active FROM support_canned_replies WHERE active ORDER BY title
`

func (q *Queries) ListCanned(ctx context.Context) ([]SupportCannedReply, error) {
	rows, err := q.db.Query(ctx, listCanned)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportCannedReply
	for rows.Next() {
		var i SupportCannedReply
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.Body,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCannedAll = `-- name: ListCannedAll :many
SELECT id, key, title, body, active FROM support_canned_replies ORDER BY title
`

func (q *Queries) ListCannedAll(ctx context.Context) ([]SupportCannedReply, error) {
	rows, err := q.db.Query(ctx, listCannedAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportCannedReply
	for rows.Next() {
		var i SupportCannedReply
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.Body,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT m.id, m.conversation_id, m.sender, m.operator_id, m.client_msg_id, m.body_enc, m.created_at, m.read_at, o.display_name AS operator_display_name
FROM support_messages m LEFT JOIN support_operators o ON o.id = m.operator_id
WHERE m.conversation_id = $1 AND m.id > $2
ORDER BY m.id ASC LIMIT $3
`

type ListMessagesAfterParams struct {
	ConversationID uuid.UUID
	ID             uuid.UUID
	Limit          int32
}

type ListMessagesAfterRow struct {
	ID                  uuid.UUID
	ConversationID      uuid.UUID
	Sender              string
	OperatorID          uuid.NullUUID
	ClientMsgID         uuid.NullUUID
	BodyEnc             []byte
	CreatedAt           time.Time
	ReadAt              *time.Time
	OperatorDisplayName *string
}

func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter, arg.ConversationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesAfterRow
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Sender,
			&i.OperatorID,
			&i.ClientMsgID,
			&i.BodyEnc,
			&i.CreatedAt,
			&i.ReadAt,
			&i.OperatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT m.id, m.conversation_id, m.sender, m.operator_id, m.client_msg_id, m.body_enc, m.created_at, m.read_at, o.display_name AS operator_display_name
FROM support_messages m LEFT JOIN support_operators o ON o.id = m.operator_id
WHERE m.conversation_id = $1 AND m.id < $2
ORDER BY m.id DESC LIMIT $3
`

type ListMessagesBeforeParams struct {
	ConversationID uuid.UUID
	ID             uuid.UUID
	Limit          int32
}

type ListMessagesBeforeRow struct {
	ID                  uuid.UUID
	ConversationID      uuid.UUID
	Sender              string
	OperatorID          uuid.NullUUID
	ClientMsgID         uuid.NullUUID
	BodyEnc             []byte
	CreatedAt           time.Time
	ReadAt              *time.Time
	OperatorDisplayName *string
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.ConversationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesBeforeRow
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Sender,
			&i.OperatorID,
			&i.ClientMsgID,
			&i.BodyEnc,
			&i.CreatedAt,
			&i.ReadAt,
			&i.OperatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesLatest = `-- name: ListMessagesLatest :many
SELECT m.id, m.conversation_id, m.sender, m.operator_id, m.client_msg_id, m.body_enc, m.created_at, m.read_at, o.display_name AS operator_display_name
FROM support_messages m LEFT JOIN support_operators o ON o.id = m.operator_id
WHERE m.conversation_id = $1
ORDER BY m.id DESC LIMIT $2
`

type ListMessagesLatestParams struct {
	ConversationID uuid.UUID
	Limit          int32
}

type ListMessagesLatestRow struct {
	ID                  uuid.UUID
	ConversationID      uuid.UUID
	Sender              string
	OperatorID          uuid.NullUUID
	ClientMsgID         uuid.NullUUID
	BodyEnc             []byte
	CreatedAt           time.Time
	ReadAt              *time.Time
	OperatorDisplayName *string
}

func (q *Queries) ListMessagesLatest(ctx context.Context, arg ListMessagesLatestParams) ([]ListMessagesLatestRow, error) {
	rows, err := q.db.Query(ctx, listMessagesLatest, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesLatestRow
	for rows.Next() {
		var i ListMessagesLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Sender,
			&i.OperatorID,
			&i.ClientMsgID,
			&i.BodyEnc,
			&i.CreatedAt,
			&i.ReadAt,
			&i.OperatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueue = `-- name: ListQueue :many
SELECT c.id, c.user_id, c.status, c.assigned_operator_id, c.last_message_at, c.awaiting_since, c.user_unread_count, c.operator_unread, c.device_meta, c.created_at, c.closed_at, op.display_name AS operator_display_name
FROM support_conversations c LEFT JOIN support_operators op ON op.id = c.assigned_operator_id
WHERE ($1::text = '' OR c.status = $1)
ORDER BY (c.awaiting_since IS NULL), c.awaiting_since ASC NULLS LAST, c.last_message_at DESC
LIMIT $2
`

type ListQueueParams struct {
	Column1 string
	Limit   int32
}

type ListQueueRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Status              string
	AssignedOperatorID  uuid.NullUUID
	LastMessageAt       time.Time
	AwaitingSince       *time.Time
	UserUnreadCount     int32
	OperatorUnread      int32
	DeviceMeta          []byte
	CreatedAt           time.Time
	ClosedAt            *time.Time
	OperatorDisplayName *string
}

func (q *Queries) ListQueue(ctx context.Context, arg ListQueueParams) ([]ListQueueRow, error) {
	rows, err := q.db.Query(ctx, listQueue, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueueRow
	for rows.Next() {
		var i ListQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.AssignedOperatorID,
			&i.LastMessageAt,
			&i.AwaitingSince,
			&i.UserUnreadCount,
			&i.OperatorUnread,
			&i.DeviceMeta,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.OperatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOperatorMessagesRead = `-- name: MarkOperatorMessagesRead :exec
UPDATE support_messages SET read_at = $3
WHERE conversation_id = $1 AND sender <> 'user' AND read_at IS NULL AND id <= $2
`

type MarkOperatorMessagesReadParams struct {
	ConversationID uuid.UUID
	ID             uuid.UUID
	ReadAt         *time.Time
}

func (q *Queries) MarkOperatorMessagesRead(ctx context.Context, arg MarkOperatorMessagesReadParams) error {
	_, err := q.db.Exec(ctx, markOperatorMessagesRead, arg.ConversationID, arg.ID, arg.ReadAt)
	return err
}

const markUserMessagesRead = `-- name: MarkUserMessagesRead :exec
UPDATE support_messages SET read_at = $3
WHERE conversation_id = $1 AND sender = 'user' AND read_at IS NULL AND id <= $2
`

type MarkUserMessagesReadParams struct {
	ConversationID uuid.UUID
	ID             uuid.UUID
	ReadAt         *time.Time
}

func (q *Queries) MarkUserMessagesRead(ctx context.Context, arg MarkUserMessagesReadParams) error {
	_, err := q.db.Exec(ctx, markUserMessagesRead, arg.ConversationID, arg.ID, arg.ReadAt)
	return err
}

const oldestAwaitingSince = `-- name: OldestAwaitingSince :one
SELECT awaiting_since FROM support_conversations WHERE status <> 'closed' AND awaiting_since IS NOT NULL ORDER BY awaiting_since ASC LIMIT 1
`

func (q *Queries) OldestAwaitingSince(ctx context.Context) (*time.Time, error) {
	row := q.db.QueryRow(ctx, oldestAwaitingSince)
	var awaiting_since *time.Time
	err := row.Scan(&awaiting_since)
	return awaiting_since, err
}

const revokeOperatorSession = `-- name: RevokeOperatorSession :exec
UPDATE operator_sessions SET revoked_at = $2 WHERE token_hash = $1
`

type RevokeOperatorSessionParams struct {
	TokenHash string
	RevokedAt *time.Time
}

func (q *Queries) RevokeOperatorSession(ctx context.Context, arg RevokeOperatorSessionParams) error {
	_, err := q.db.Exec(ctx, revokeOperatorSession, arg.TokenHash, arg.RevokedAt)
	return err
}

const revokeOperatorSessions = `-- name: RevokeOperatorSessions :exec
UPDATE operator_sessions SET revoked_at = $2 WHERE operator_id = $1 AND revoked_at IS NULL
`

type RevokeOperatorSessionsParams struct {
	OperatorID uuid.UUID
	RevokedAt  *time.Time
}

func (q *Queries) RevokeOperatorSessions(ctx context.Context, arg RevokeOperatorSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOperatorSessions, arg.OperatorID, arg.RevokedAt)
	return err
}

const setOperatorActive = `-- name: SetOperatorActive :execrows
UPDATE support_operators SET active = $2 WHERE username = $1
`

type SetOperatorActiveParams struct {
	Username string
	Active   bool
}

func (q *Queries) SetOperatorActive(ctx context.Context, arg SetOperatorActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOperatorActive, arg.Username, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOperatorPassword = `-- name: SetOperatorPassword :execrows
UPDATE support_operators SET password_hash = $2 WHERE username = $1
`

type SetOperatorPasswordParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) SetOperatorPassword(ctx context.Context, arg SetOperatorPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOperatorPassword, arg.Username, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserUnread = `-- name: SetUserUnread :exec
UPDATE support_conversations SET user_unread_count = (
  SELECT count(*) FROM support_messages WHERE conversation_id = $1 AND sender <> 'user' AND read_at IS NULL)
WHERE id = $1
`

func (q *Queries) SetUserUnread(ctx context.Context, conversationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserUnread, conversationID)
	return err
}

const touchOperatorLogin = `-- name: TouchOperatorLogin :exec
UPDATE support_operators SET last_login_at = $2 WHERE id = $1
`

type TouchOperatorLoginParams struct {
	ID          uuid.UUID
	LastLoginAt *time.Time
}

func (q *Queries) TouchOperatorLogin(ctx context.Context, arg TouchOperatorLoginParams) error {
	_, err := q.db.Exec(ctx, touchOperatorLogin, arg.ID, arg.LastLoginAt)
	return err
}

const upsertCanned = `-- name: UpsertCanned :exec
INSERT INTO support_canned_replies (id, key, title, body, active) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body, active = EXCLUDED.active
`

type UpsertCannedParams struct {
	ID     uuid.UUID
	Key    string
	Title  string
	Body   string
	Active bool
}

func (q *Queries) UpsertCanned(ctx context.Context, arg UpsertCannedParams) error {
	_, err := q.db.Exec(ctx, upsertCanned,
		arg.ID,
		arg.Key,
		arg.Title,
		arg.Body,
		arg.Active,
	)
	return err
}
