// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trials.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTrialByDeviceHash = `-- name: GetTrialByDeviceHash :one
SELECT id, user_id, device_hash, started_at, ends_at FROM trials WHERE device_hash = $1
`

func (q *Queries) GetTrialByDeviceHash(ctx context.Context, deviceHash string) (Trial, error) {
	row := q.db.QueryRow(ctx, getTrialByDeviceHash, deviceHash)
	var i Trial
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceHash,
		&i.StartedAt,
		&i.EndsAt,
	)
	return i, err
}

const getTrialByUser = `-- name: GetTrialByUser :one
SELECT id, user_id, device_hash, started_at, ends_at FROM trials WHERE user_id = $1
`

func (q *Queries) GetTrialByUser(ctx context.Context, userID uuid.UUID) (Trial, error) {
	row := q.db.QueryRow(ctx, getTrialByUser, userID)
	var i Trial
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceHash,
		&i.StartedAt,
		&i.EndsAt,
	)
	return i, err
}

const insertTrial = `-- name: InsertTrial :exec
INSERT INTO trials (id, user_id, device_hash, started_at, ends_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertTrialParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DeviceHash string
	StartedAt  time.Time
	EndsAt     time.Time
}

func (q *Queries) InsertTrial(ctx context.Context, arg InsertTrialParams) error {
	_, err := q.db.Exec(ctx, insertTrial,
		arg.ID,
		arg.UserID,
		arg.DeviceHash,
		arg.StartedAt,
		arg.EndsAt,
	)
	return err
}
