// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at) VALUES ($1, $2) RETURNING id, created_at, status, phone_e164, phone_verified_at, deleted_at
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.CreatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.PhoneE164,
		&i.PhoneVerifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, status, phone_e164, phone_verified_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.PhoneE164,
		&i.PhoneVerifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users SET status = 'deleted', deleted_at = $2, phone_e164 = NULL, phone_verified_at = NULL
WHERE id = $1 AND status = 'active'
`

type SoftDeleteUserParams struct {
	ID        uuid.UUID
	DeletedAt *time.Time
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
