// Maps goals to sticker ids under assets/art/emoji/ (see EmojiArt).
// Lookup order: the goal itself, its goal-library icon key, its care area, then the flag.

/// Goals whose library icon key is shared with another goal that needs a different sticker.
const Map<String, String> _goalEmoji = {
  'calm_face_wash': 'body/sweat_droplets',
  'calm_music_one': 'tech/headphones',
  'calm_tea_slow': 'food/tea_glass',
  'calm_worry_paper': 'misc/paper_ball',
  'conn_old_photo': 'home/photo_frame',
  'conn_short_message': 'connection/love_letter',
  'conn_thank_someone': 'connection/thank_card',
  'conn_voice_note': 'tech/microphone',
  'focus_break_walk': 'misc/pause',
  'focus_finish_one': 'misc/finish_flag',
  'focus_top_three': 'misc/checklist',
  'food_breakfast': 'food/bread_jam',
  'food_plan_meal': 'food/meal_plan',
  'food_slow_bites': 'food/sandwich',
  'food_veggie_side': 'food/salad',
  'food_water_four': 'food/water_bottle',
  'home_bed_make': 'home/pillow',
  'home_clothes_fold': 'clothing/tshirt',
  'home_dishes_few': 'home/clean_plate',
  'home_five_minute_tidy': 'misc/stopwatch',
  'home_one_corner': 'home/laundry_basket',
  'kind_gratitude_view': 'hands/folded_hands',
  'kind_hand_heart': 'hearts/orange_heart',
  'kind_three_good': 'misc/star',
  'move_neck_roll': 'people/neck_roll',
  'move_stairs': 'home/stairs',
  'move_stretch_morning': 'nature/sun_face',
  'move_walk_phone': 'people/walking_phone',
  'sleep_dim_lights': 'home/lamp',
  'sleep_early_dinner': 'food/dinner_moon',
  'sleep_no_late_tea': 'food/no_tea',
  'sleep_stretch_bed': 'people/stretching',
};

const Map<String, String> _iconEmoji = {
  'accessibility': 'people/person_raising_hand',
  'accessibility_new': 'faces/relieved',
  'air': 'body/lungs',
  'alarm': 'home/alarm_clock',
  'apple': 'food/apple',
  'backpack': 'misc/backpack',
  'balance': 'calm/dove_peace',
  'bed': 'home/bed',
  'bedtime': 'calm/zzz',
  'block': 'hands/raised_hand',
  'call': 'connection/telephone',
  'card_giftcard': 'misc/gift',
  'celebration': 'hands/clapping_hands',
  'center_focus_strong': 'misc/target',
  'chat': 'connection/speech_bubble',
  'checklist': 'misc/notepad_pencil',
  'checkroom': 'clothing/tshirt',
  'cleaning_services': 'home/broom',
  'coffee': 'food/matcha',
  'cookie': 'food/croissant',
  'delete': 'home/trash_bin',
  'deck': 'nature/landscape',
  'desk': 'tech/keyboard',
  'dinner_dining': 'food/cutlery',
  'directions_walk': 'hobbies/sneaker',
  'draw': 'misc/notepad_pencil',
  'eco': 'nature/herb_sprig',
  'edit_note': 'misc/notepad_pencil',
  'emoji_food_beverage': 'food/matcha',
  'event': 'ui/calendar',
  'face': 'home/mirror',
  'fact_check': 'misc/magnifier',
  'favorite': 'hearts/sparkling_heart',
  'flag': 'misc/flag_in_hole',
  'free_breakfast': 'food/frying_pan_egg',
  'grain': 'food/nuts',
  'groups': 'connection/people_hugging',
  'healing': 'faces/hugging',
  'hearing': 'body/ear',
  'hiking': 'hobbies/footprints',
  'inventory_2': 'home/drawers',
  'light': 'calm/candle',
  'light_mode': 'calm/candle',
  'local_cafe': 'food/matcha',
  'local_drink': 'food/water_glass',
  'local_florist': 'nature/flower',
  'menu_book': 'misc/book',
  'mic': 'connection/speech_bubble',
  'military_tech': 'misc/medal_first',
  'music_note': 'hobbies/music_note',
  'nightlife': 'hobbies/dancing',
  'notifications_off': 'tech/bell_off',
  'park': 'nature/leafy_plant',
  'pedal_bike': 'hobbies/bicycle',
  'phone_off': 'tech/phone_off',
  'photo': 'connection/selfie',
  'restaurant': 'food/cutlery',
  'schedule': 'ui/clock',
  'school': 'body/brain',
  'self_improvement': 'calm/meditation',
  'sentiment_satisfied': 'faces/smiling_blush',
  'shower': 'hygiene/shower',
  'smartphone': 'tech/smartphone',
  'soup_kitchen': 'food/frying_pan_egg',
  'spa': 'calm/meditation',
  'stairs': 'home/ladder',
  'task_alt': 'misc/flag_in_hole',
  'timer': 'misc/hourglass',
  'volunteer_activism': 'hands/folded_hands',
  'water_drop': 'food/water_glass',
  'waving_hand': 'hands/waving_hand',
  'wb_sunny': 'nature/sunrise',
  'weekend': 'connection/teddy_bear',
  'window': 'home/window',
};

const Map<String, String> _areaEmoji = {
  'sleep': 'calm/zzz',
  'calm': 'calm/meditation',
  'movement': 'hobbies/sneaker',
  'nutrition': 'food/apple',
  'connection': 'hearts/two_hearts',
  'focus': 'misc/target',
  'self_kindness': 'nature/sunflower',
  'home': 'nav/home',
};

/// An [icon] that is already a sticker id (chosen by the user, e.g. `food/apple`) wins over everything.
String goalEmoji({String? goalKey, String? icon, String? area}) =>
    (icon != null && icon.contains('/') ? icon : null) ?? _goalEmoji[goalKey] ?? _iconEmoji[icon] ?? _areaEmoji[area] ?? 'misc/flag_in_hole';
