// Generates lib/core/analytics/analytics_event.dart from config-data/analytics/events.json,
// the single source of truth shared with the Go allowlist (docs/70 §7).
// Run from app/: dart run tool/gen_analytics_events.dart [--check]
import 'dart:convert';
import 'dart:io';

String camel(String s) {
  final p = s.split('_');
  return p.first + p.skip(1).map((e) => e[0].toUpperCase() + e.substring(1)).join();
}

void main(List<String> args) {
  final cat = jsonDecode(File('../config-data/analytics/events.json').readAsStringSync()) as Map<String, dynamic>;
  final events = (cat['events'] as List).cast<Map<String, dynamic>>();
  final common = (cat['common_props'] as Map<String, dynamic>).keys.toList()..sort();
  final forbidden = (cat['forbidden_props'] as List).cast<String>();
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_analytics_events.dart from config-data/analytics/events.json. DO NOT EDIT.')
    ..writeln()
    ..writeln('/// Client-sendable analytics events (server-side events are excluded).')
    ..writeln('enum AnalyticsEvent {');
  final client = events.where((e) => e['server_side'] != true).toList();
  for (var i = 0; i < client.length; i++) {
    final e = client[i];
    final props = (e['props'] as Map<String, dynamic>).keys.toList()..sort();
    b.writeln("  ${camel(e['name'] as String)}('${e['name']}', {${props.map((p) => "'$p'").join(', ')}})${i == client.length - 1 ? ';' : ','}");
  }
  b
    ..writeln()
    ..writeln('  const AnalyticsEvent(this.wireName, this.allowedProps);')
    ..writeln('  final String wireName;')
    ..writeln('  final Set<String> allowedProps;')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Props added automatically to every event.')
    ..writeln('const analyticsCommonProps = <String>{${common.map((p) => "'$p'").join(', ')}};')
    ..writeln()
    ..writeln('/// Prop name prefixes allowed on every event (experiment variants).')
    ..writeln("const analyticsCommonPrefixes = <String>['exp_'];")
    ..writeln()
    ..writeln('/// Never sent, whatever the caller passes (docs/70 §1).')
    ..writeln('const analyticsForbiddenProps = <String>{${forbidden.map((p) => "'$p'").join(', ')}};');
  final out = File('lib/core/analytics/analytics_event.dart');
  if (args.contains('--check')) {
    if (!out.existsSync() || out.readAsStringSync() != b.toString()) {
      stderr.writeln('analytics_event.dart is stale; run dart run tool/gen_analytics_events.dart');
      exit(1);
    }
    return;
  }
  out.writeAsStringSync(b.toString());
}
