// GENERATED by tool/gen_analytics_events.dart from config-data/analytics/events.json. DO NOT EDIT.

/// Client-sendable analytics events (server-side events are excluded).
enum AnalyticsEvent {
  appInstalled('app_installed', {}),
  appOpened('app_opened', {'source'}),
  onboardingStepViewed('onboarding_step_viewed', {'step'}),
  onboardingCompleted('onboarding_completed', {'cat_name_changed', 'habits_selected_count', 'notif_permission'}),
  habitCreated('habit_created', {'has_reminder', 'template_key'}),
  firstHabitCreated('first_habit_created', {'template_key'}),
  habitCompleted('habit_completed', {'source', 'template_key'}),
  checkinCompleted('checkin_completed', {'has_note', 'source'}),
  exerciseStarted('exercise_started', {'exercise_key'}),
  exerciseCompleted('exercise_completed', {'duration_s', 'exercise_key'}),
  adventureStarted('adventure_started', {'duration_minutes', 'location_key'}),
  adventureClaimed('adventure_claimed', {'coins', 'got_item', 'location_key'}),
  shopItemPurchased('shop_item_purchased', {'item_key', 'price_coins'}),
  itemEquipped('item_equipped', {'item_key', 'slot'}),
  streakUpdated('streak_updated', {'current', 'freeze_used'}),
  paywallViewed('paywall_viewed', {'trigger', 'variant'}),
  paywallPlanSelected('paywall_plan_selected', {'product_id'}),
  paywallClosed('paywall_closed', {'trigger'}),
  trialStarted('trial_started', {'provisional'}),
  trialEnded('trial_ended', {'converted'}),
  purchaseStarted('purchase_started', {'product_id'}),
  purchaseCompleted('purchase_completed', {'kind', 'product_id'}),
  purchaseFailed('purchase_failed', {'product_id', 'reason'}),
  restoreCompleted('restore_completed', {'restored_count'}),
  notificationOpened('notification_opened', {'type'}),
  safetyScreenViewed('safety_screen_viewed', {'source'}),
  settingsChanged('settings_changed', {'key'}),
  forceUpdateShown('force_update_shown', {'kind'});

  const AnalyticsEvent(this.wireName, this.allowedProps);
  final String wireName;
  final Set<String> allowedProps;
}

/// Props added automatically to every event.
const analyticsCommonProps = <String>{'app_version', 'install_age_days', 'is_premium', 'market', 'session_id', 'trial_state'};

/// Prop name prefixes allowed on every event (experiment variants).
const analyticsCommonPrefixes = <String>['exp_'];

/// Never sent, whatever the caller passes (docs/70 §1).
const analyticsForbiddenProps = <String>{'mood_level', 'note', 'text', 'title', 'phone'};
